stages:
  - release

semantic-release:
  image: node:14
  stage: release
  only:
    refs:
    - main
    - preview
    # This matches maintenance branches
    - /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
  script:
    # install dependencies
    - >
      npm install --no-save
      @semantic-release/exec
      @semantic-release/npm
      @semantic-release/git
      @semantic-release/gitlab
      @semantic-release/changelog
      @commitlint/cli
      @commitlint/config-conventional
    # run semantic-release
    - npx semantic-release
